name: PR Map
on:
  pull_request:
    branches: [main, feature1]
jobs:
  Pull Request Check:
    runs-on: ubuntu-latest

    steps:
    - name: Pull submodule dependencies
      uses: ivanbakel/submodule-dependency@v0.1.2.1